### ISSUE TITLE
where_has not using the correct table name

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#751]
Turns out the weird error happened before was because my poetry virtual environment...
After reset all things up, it seems dot relation still not working,
the column 'category' should be in contract_supports table.

Masonite-orm version:
![image](https://user-images.githubusercontent.com/103096852/177715506-f318b708-1edb-4372-a5c6-636750e4cea3.png)

Here's the error message:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/leanne.tang/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 415, in <module>
    mysql_test_connect()
  File "/Users/leanne.tang/Documents/Projects/Masonite-orm-test/app/services/orator_update.py", line 356, in mysql_test_connect
    abc = models.A.abc().get()
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-2UYfFVGQ-py3.10/lib/python3.10/site-packages/masoniteorm/query/QueryBuilder.py", line 1936, in get
    result = self.new_connection().query(self.to_qmark(), self._bindings)
  File "/Users/leanne.tang/Library/Caches/pypoetry/virtualenvs/Masonite-orm-test1-2UYfFVGQ-py3.10/lib/python3.10/site-packages/masoniteorm/connections/PostgresConnection.py", line 162, in query
    raise QueryException(str(e)) from e
masoniteorm.exceptions.QueryException: column contracts.category does not exist
```

_Originally posted by @leannextang in https://github.com/MasoniteFramework/orm/issues/744#issuecomment-1177188538_

**Comment by josephmancuso** [comment]
Fixed in #764
